---
title: "LoL PCA"
author: "Emil Jessen"
date: "23 sep 2020"
output: html_document
---
```{r}
library(pacman)

p_load(rvest, tidyverse, stats, ggplot2, ggrepel)
```

Load data
```{r}
df <- read.csv("C:/Users/Lenovo/Desktop/wd/cultural_data_science/PCA_on_LoL_dataset/LoLBaseStats.csv")

#create rownames (names of champions)
row.names(df) <- df$Champion

# only have numerical columns (excluding column 1 and 8)
df <- cbind(df[,2:7],df[,9:19])

# AS+ is with percentage signs, and therefore not numeric
df$AS. <- gsub("\\+", "", df$AS.)
df$AS. <- gsub("\\%", "", df$AS.)
df$AS. <- as.numeric(df$AS.)
```

PCA
```{r}
# only doing it on half the champions, for better visuals
df1 <- df
df = df[seq(1, nrow(df), 2), ]


pca <- prcomp(df, scale=T)
summary(pca)
plot(pca)
dim(df)
plot(pca$x[,1],pca$x[,2])

pca_data <- data.frame(champion = rownames(pca$x),
                       X = pca$x[,1],
                       Y = pca$x[,2])



pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)

ggplot(data=pca_data, aes(x=X, y=Y, label=champion)) +
  # geom_text(aes(label=champion), hjust=0, vjust=0) +
  geom_label_repel(aes(label = champion),
                  box.padding   = 0.15, 
                  point.padding = 0.1,
                  label.size = 0.1,
                  segment.color = 'grey50') +
  theme_classic() +
  geom_point() +
  xlab(paste("PC1 - ", pca.var.per[1], "%", sep="")) +
  ylab(paste("PC2 - ", pca.var.per[2], "%", sep="")) +
  theme_bw() +
  ggtitle("PCA on BaseStats for Champions in LoL")

```

Visualization of champions by stats
```{r}
colnames(df1)
df1 <- scale(df1)
df1 <- as.data.frame(df1)
df1$offensive <- df1$AD + df1$AD. + df1$AS + df1$AS.
df1$defensive <- df1$AR + df1$AR. + df1$HP + df1$HP. + df1$HP5 + df1$HP5. + df1$MR + df1$MR.   

df1$champion <- rownames(df1)
df1$range <- df$Range
df1$ranged <- ifelse(df1$range > 299, 1, 0)

ggplot(data=df1[df1$ranged == "1",], aes(x = offensive, y = defensive, label = champion )) +
    geom_label_repel(aes(label = champion),
                  box.padding   = 0.15, 
                  point.padding = 0.1,
                  label.size = 0.1,
                  segment.color = 'grey50') +
  theme_classic() +
  geom_point() +
  xlab("offensive stats") +
  ylab("defensive stats") +
  theme_bw() +
  ggtitle("offensive stats vs defensive stats")
  
ggplot(data=df1[df1$ranged == "0",], aes(x = offensive, y = defensive, label = champion )) +
    geom_label_repel(aes(label = champion),
                  box.padding   = 0.15, 
                  point.padding = 0.1,
                  label.size = 0.1,
                  segment.color = 'grey50') +
  theme_classic() +
  geom_point() +
  xlab("offensive stats") +
  ylab("defensive stats") +
  theme_bw() +
  ggtitle("offensive stats vs defensive stats")
  

```

